version: 0.2

phases:

  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean package
  post_build:
    commands:
      - echo "Uploading artifacts to S3 or deploying to AWS Elastic Beanstalk, etc."
      - # Add your deployment steps her
artifacts:
  files:
    - target/test.jar
  discard-paths: yes

